language: node_js
node_js:
  - "9"
cache:
    yarn: true
script: 
  - yarn build
  - yarn test
deploy:
  provider: gcs
  access_key_id: GOOGLNNCWKFXELJCXFBT
  secret_access_key:
    secure: "oDHstdU0FxIeDDnRyidDqdygYYnVeFuOYLrux20dhAofB3L3NOV7oRIOGLjkgQxYUrTnVUQrSd7kg627luTQWXdEolL8hK9JYDHzJLnm8vVQ1Et7omkW1gwtxF/YTs0s7dXBGlJ0X2011k+ifY1SofkIEjtagKXu0SOiMgHMpm3vQCl6cc1pJKo+LocZLMRFHRYgW7LcmV7UD3g8EBg3y4cUefpCDEpOtREzYjlWCaTOnM5hNWFtZp9U0/Y9TO5AQzCioY+0nQkPMM5yQTpFZWPs5tLgUkiZAE5FtymgXQWVMRyh4EBiYdP5vDcPh+PwW8Hi7X7tc+KgQzXfkf8VL+pAFMeF6XC8D8A99gfM+s43y0atxMeswFBbDhQlCr/8zGi+TW3DI/+k/hRtoBCXP2QSpsaMvLv/uwAcMQ+7cdu+Hp34Hbd7aohMuAa4rHrQJcCWEL9Q+raxtlzpxe7ydfgbzJWudWjUFbdiouWz3BtSLUEkgIp9bzLt0qVtF7ZQXRSMjWhModGMMUZ/DfzzJPfg+9UHtCVAsBGiFgzb9CjqzDgJ7p8sBwgy62/8p5hgLHCZSitm0N4tRhRZqdQDvwVAmaFEnExy55Ob6o188UbzyszAetuHXXTKJ5P6qnn06dSfPaPpvIO9LztEIz50XkBGI4/WYOwvTzJkZ0PyLK0="
  bucket: prysmaticlabs.com
  acl: public-read
  local-dir: build
  skip_cleanup: true
  on:
    repo: prysmaticlabs/website
    branch: master
